#!/usr/bin/env python3
from __future__ import annotations
import argparse, importlib.util, json, sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
SERVER=ROOT/'repo_scaffold/app/server.py'

def load_server():
    spec=importlib.util.spec_from_file_location('bbtc_server_for_pilot_pack', SERVER)
    mod=importlib.util.module_from_spec(spec)
    assert spec and spec.loader
    spec.loader.exec_module(mod)
    return mod

def main() -> int:
    ap=argparse.ArgumentParser(description='Generate a live pilot acceptance pack without starting the web server.')
    ap.add_argument('--owner-note', default='Generated by offline pilot acceptance pack script.')
    args=ap.parse_args()
    mod=load_server()
    result=mod.create_pilot_acceptance_pack(args.owner_note)
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0 if result.get('ok') else 1
if __name__=='__main__': sys.exit(main())
